import {
  abcdef,
  abcdefMergeStyles,
  abyss,
  abyssMergeStyles,
  androidStudio,
  androidStudioMergeStyles,
  andromeda,
  andromedaMergeStyles,
  applyMergeRevertStyles,
  basicDark,
  basicDarkMergeStyles,
  basicLight,
  basicLightMergeStyles,
  forest,
  forestMergeStyles,
  githubDark,
  githubDarkMergeStyles,
  githubLight,
  githubLightMergeStyles,
  gruvboxDark,
  gruvboxDarkMergeStyles,
  gruvboxLight,
  gruvboxLightMergeStyles,
  materialDark,
  materialDarkMergeStyles,
  materialLight,
  materialLightMergeStyles,
  monokai,
  monokaiMergeStyles,
  nord,
  nordMergeStyles,
  palenight,
  palenightMergeStyles,
  solarizedDark,
  solarizedDarkMergeStyles,
  solarizedLight,
  solarizedLightMergeStyles,
  tokyoNightDay,
  tokyoNightDayMergeStyles,
  tokyoNightStorm,
  tokyoNightStormMergeStyles,
  volcano,
  volcanoMergeStyles,
  vsCodeDark,
  vsCodeDarkMergeStyles,
  vsCodeLight,
  vsCodeLightMergeStyles,
} from '../../packages/bundle/src';

const themes = [
  {
    name: 'abcdef',
    extension: abcdef,
    mergeStyles: abcdefMergeStyles,
  },
  {
    name: 'abyss',
    extension: abyss,
    mergeStyles: abyssMergeStyles,
  },
  {
    name: 'android-studio',
    extension: androidStudio,
    mergeStyles: androidStudioMergeStyles,
  },
  {
    name: 'andromeda',
    extension: andromeda,
    mergeStyles: andromedaMergeStyles,
  },
  {
    name: 'basic-dark',
    extension: basicDark,
    mergeStyles: basicDarkMergeStyles,
  },
  {
    name: 'basic-light',
    extension: basicLight,
    mergeStyles: basicLightMergeStyles,
  },
  {
    name: 'forest',
    extension: forest,
    mergeStyles: forestMergeStyles,
  },
  {
    name: 'github-dark',
    extension: githubDark,
    mergeStyles: githubDarkMergeStyles,
  },
  {
    name: 'github-light',
    extension: githubLight,
    mergeStyles: githubLightMergeStyles,
  },
  {
    name: 'gruvbox-dark',
    extension: gruvboxDark,
    mergeStyles: gruvboxDarkMergeStyles,
  },
  {
    name: 'gruvbox-light',
    extension: gruvboxLight,
    mergeStyles: gruvboxLightMergeStyles,
  },
  {
    name: 'material-dark',
    extension: materialDark,
    mergeStyles: materialDarkMergeStyles,
  },
  {
    name: 'material-light',
    extension: materialLight,
    mergeStyles: materialLightMergeStyles,
  },
  {
    name: 'monokai',
    extension: monokai,
    mergeStyles: monokaiMergeStyles,
  },
  {
    name: 'nord',
    extension: nord,
    mergeStyles: nordMergeStyles,
  },
  {
    name: 'palenight',
    extension: palenight,
    mergeStyles: palenightMergeStyles,
  },
  {
    name: 'solarized-dark',
    extension: solarizedDark,
    mergeStyles: solarizedDarkMergeStyles,
  },
  {
    name: 'solarized-light',
    extension: solarizedLight,
    mergeStyles: solarizedLightMergeStyles,
  },
  {
    name: 'tokyo-night-storm',
    extension: tokyoNightStorm,
    mergeStyles: tokyoNightStormMergeStyles,
  },
  {
    name: 'tokyo-night-day',
    extension: tokyoNightDay,
    mergeStyles: tokyoNightDayMergeStyles,
  },
  {
    name: 'volcano',
    extension: volcano,
    mergeStyles: volcanoMergeStyles,
  },
  {
    name: 'vscode-dark',
    extension: vsCodeDark,
    mergeStyles: vsCodeDarkMergeStyles,
  },
  {
    name: 'vscode-light',
    extension: vsCodeLight,
    mergeStyles: vsCodeLightMergeStyles,
  },
];

export { applyMergeRevertStyles, themes };
