name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

parameters:
  - name: source_template_repo
    type: string
    default: ''
    displayName: 'Reference to the template repo'
  - name: template_reference
    type: string
    default: ''
    displayName: 'Reference of the template to be executed'

trigger:
  - main

pool:
  vmImage: $(vmImageName)

resources:
  repositories:
    - repository: common
      type: git
      name: ${{ parameters.source_template_repo }}
      ref: main

stages:
  - stage: GetSources
    jobs:
      - job: GetGitHubSources
        steps:
          - template: ${{ parameters.template_reference }}@common
            parameters:
              source_repo_url: $(SOURCE-REPO-URL)
              source_repo_pat: $(SOURCE-REPO-PAT)
              destination_repo_url: $(DESTINATION-REPO-URL)
              destination_repo_pat: $(DESTINATION-REPO-PAT)