name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

variables:
  vmImageName: 'ubuntu-latest'  # Agent VM image name

trigger:
  - main

pool:
  vmImage: $(vmImageName)

resources:
  repositories:
    - repository: common
      type: git
      name: Templates/CommonScripts
      ref: main

stages:
  - stage: GetSources
    jobs:
      - job: GetGitHubSources
        steps:
          - template: /ado/steps/utils/copy-branch.yml@common
            parameters:
              source_repo_url: $(SOURCE-REPO-URL)
              source_repo_pat: $(SOURCE-REPO-PAT)
              destination_repo_url: $(DESTINATION-REPO-URL)
              destination_repo_pat: $(DESTINATION-REPO-PAT)