name: Bug Report
description: File a bug report for @fsegurai/codemirror-themes.
title: "[Bug]"
labels: bug
body:
  - type: textarea
    id: issue
    attributes:
      label: Description of the issue
      description: What's the issue you encountered?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How can the issue be reproduced?
      placeholder: Describe each step as precisely as possible
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log file
      description: A log file will help our developers to better diagnose and fix the issue.
      placeholder: Paste the log file here
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of the software are you using?
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "e.g. Windows 10"
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: "e.g. Chrome"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context?
      description: |
        - Additional info about your environment:
        - Any other information relevant to your issue.
    validations:
      required: false
