blank_issues_enabled: false
contact_links:
  - name: @fsegurai/codemirror-themes Issues
    url: https://github.com/fsegurai/codemirror-themes/issues
    about: This is for development, support and technical issues/questions.
