name: Build Lib-Demo

on:
  workflow_call:

env:
  LIB_ARTIFACT_NAME: 'build-lib-artifact'

jobs:
  build_library:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    environment: FSI_DEP_NodeJs
    strategy:
      matrix:
        package:
          [
            abcdef,
            abyss,
            android-studio,
            andromeda,
            basic-dark,
            basic-light,
            forest,
            github-dark,
            github-light,
            gruvbox-dark,
            gruvbox-light,
            material-dark,
            material-light,
            monokai,
            nord,
            solarized-dark,
            solarized-light,
            tokyo-night-day,
            tokyo-night-storm,
            volcano,
            bundle
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js - Version ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci # package-lock.json is present

      - name: Build ${{ matrix.package }} package
        run: |
          cd packages/${{ matrix.package }}
          npm run prepare

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LIB_ARTIFACT_NAME }}-${{ matrix.package }}
          path: packages/${{ matrix.package }}/dist
          if-no-files-found: error

  build_demo:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    environment: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js - Version ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci # package-lock.json is present

      - name: Build demo
        run: |
          npm run build:demo
          npm run postBuild:demo
