name: Build Lib-Demo

on:
  workflow_call:

env:
  LIB_ARTIFACT_NAME: 'build-lib-artifact'

jobs:
  build_library:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    environment: FSI_DEP_NodeJs
    strategy:
      matrix:
        package:
          [
            abcdef,
            abyss,
            android-studio,
            andromeda,
            basic-dark,
            basic-light,
            forest,
            github-dark,
            github-light,
            gruvbox-dark,
            gruvbox-light,
            material-dark,
            material-light,
            monokai,
            nord,
            solarized-dark,
            solarized-light,
            tokyo-night-day,
            tokyo-night-storm,
            volcano,
            bundle
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Cache bun modules
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build ${{ matrix.package }} package
        run: |
          cd packages/${{ matrix.package }}
          bun run prepare

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LIB_ARTIFACT_NAME }}-${{ matrix.package }}
          path: packages/${{ matrix.package }}/dist
          if-no-files-found: error

  build_demo:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    environment: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Cache bun modules
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build demo
        run: bun run build
