name: Test Lib-Demo
# Job will only run on push and pull requests to the main branch

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'assets/**'
      - 'demo/public/**'
      - '*.yml'
      - '*.json'
      - '*.config'
      - '*.md'
      - '!package.json'
      - '!github/workflows/**'
  workflow_dispatch:
    inputs: {}
  workflow_call:
  workflow_run:
    workflows: ['Build PR']
    types: [completed]

jobs:
  build_project:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: FSI_DEP_NodeJs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun - Version ${{ vars.BUN_VERSION }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}

      - name: Install dependencies
        run: bun install

      - name: Zip artifact for te
        run: zip release.zip ./* -r

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  test_library:
    runs-on: ubuntu-latest
    needs: build_project
    timeout-minutes: 2
    environment: FSI_DEP_NodeJs
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./workspace

      - name: list files
        run: ls -la

      - name: Set up Bun - Version ${{ vars.BUN_VERSION }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}

      - name: Test Lint (Library)
        working-directory: ./workspace
        run: bun run lint:packages

  test_demo:
    runs-on: ubuntu-latest
    needs: build_project
    timeout-minutes: 2
    environment: FSI_DEP_NodeJs
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./workspace

      - name: Set up Bun - Version ${{ vars.BUN_VERSION }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}

      - name: Test Lint (Demo)
        working-directory: ./workspace
        run: npm run lint:demo