name: Test Lib-Demo
# Job will only run on push and pull requests to the main branch

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'assets/**'
      - 'demo/public/**'
      - '*.yml'
      - '*.json'
      - '*.config'
      - '*.md'
      - '!package.json'
      - '!github/workflows/**'
  workflow_dispatch:
    inputs: {}
  workflow_call:
  workflow_run:
    workflows: ['Build PR']
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: FSI_DEP_NodeJs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Test Lint (Library)
        run: npm run lint:packages

      - name: Test Lint (Demo)
        run: npm run lint:demo
